spring:
  liquibase:
    enabled: true
    change-log: "classpath:db/changelog/db.changelog-persistence.xml"
    password:
  jpa:
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        jdbc:
          batch_size: 20
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mancala
    username: vilda
    password: mancalaVilda
  h2:
    console:
      enabled: true
      path: /h2

#logging application
logging:
  level:
    com.vilda.mancala.mancalaapp: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework: INFO
