openapi: 3.0.1
info:
  version: 1.0.0
  title: Mancala game service api
  description: ""
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /service-api/v1/mancala/status/{gameId}:
    get:
      summary: Start a game
      description: "# Update Service Agreement State - `PUT`\r\n\r\nUpdates status\
        \ for a specific service agreement.\r\n"
      operationId: gameStatus
      tags:
        - mancalaService
      parameters:
        - name: gameId
          in: path
          required: true
          description: The game id in which a move will be made
          schema:
            type: string
            pattern: '^[1-9]\d*$'
          examples:
            example:
              summary: example
              value: 2002
      responses:
        "200":
          description: User has access to the given arrangement.
          content:
            application/json:
              example: {}
components:
  schemas:
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string